import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/utils/functions";
import { Marcellus } from "next/font/google";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const marcellus = Marcellus({
  weight: ["400"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(marcellus.className, "antialiased")}>
        <div
          className={
            "relative w-full min-h-screen bg-cover flex justify-center px-5"
          }
        >
          <Image
            className="absolute inset-0 left-1/2 -translate-x-1/2 top-0 -translate-y-1/2 select-none pointer-events-none animate-pulse"
            src="/hex-fade.png"
            width={600}
            height={600}
            alt="Hexagon pattern"
          />
          {children}
        </div>
      </body>
    </html>
  );
}
